import { checkPDFInput } from './pdf-browser.mjs';
import { checkAutoplayWakeLock } from './wake-lock-browser.mjs';
import { checkHeadingFocus } from './heading-focus.mjs';
import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { extract } from '../src/extract.js';
const server = createServer(async (req, res) => {
  const name = new URL(req.url, 'http://localhost').pathname.slice(1) || 'demo.html';
  try { res.setHeader('Content-Type', (name.endsWith('.js') || name.endsWith('.mjs')) ? 'text/javascript' : name.endsWith('.css') ? 'text/css' : 'text/html'); res.end(await readFile(new URL(`../dist/${name}`, import.meta.url))); }
  catch { res.statusCode = 404; res.end(); }
}).listen(0, '127.0.0.1');
await new Promise(resolve => server.once('listening', resolve));
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/Applications/Chromium.app/Contents/MacOS/Chromium', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/demo.html`);
  const original = await page.locator('article').innerHTML();
  await page.getByRole('button', { name: 'Start reading' }).click();
  const word = page.locator('.word');
  assert.ok(await word.isVisible());
  assert.equal(await page.locator('#min-speed').inputValue(), '300');
  assert.equal(await page.locator('#max-speed').inputValue(), '900');
  await page.locator('#max-speed').fill('500'); await page.locator('#max-speed').press('Tab');
  await page.locator('#speed').fill('1200'); await page.locator('#speed').press('Tab');
  assert.equal(await page.locator('#speed').inputValue(), '500');
  await page.locator('#min-speed').fill('600'); await page.locator('#min-speed').press('Tab');
  assert.equal(await page.locator('#max-speed').inputValue(), '600');
  await page.locator('#min-speed').fill(''); await page.locator('#min-speed').press('Tab');
  assert.equal(await page.locator('#min-speed').inputValue(), '600');
  await page.locator('#min-speed').fill('300'); await page.locator('#min-speed').press('Tab');
  await page.locator('#max-speed').fill('900'); await page.locator('#max-speed').press('Tab');
  await page.locator('#speed').fill('300'); await page.locator('#speed').press('Tab');
  await page.locator('dialog').focus();
  // Pace controls change the configured speed without starting playback.
  await page.keyboard.press('PageUp'); assert.equal(await page.locator('#speed').inputValue(), '325');
  await page.keyboard.press('PageDown'); assert.equal(await page.locator('#speed').inputValue(), '300');
  await page.keyboard.press('+'); assert.equal(await page.locator('#speed').inputValue(), '325');
  await page.keyboard.press('-'); assert.equal(await page.locator('#speed').inputValue(), '300');
  assert.equal(await page.locator('#play').textContent(), 'Play');
  // Clicking pace buttons must not capture subsequent playback shortcuts.
  await page.getByRole('button', { name: 'Increase speed' }).click();
  await page.keyboard.press('Enter'); assert.equal(await page.locator('#play').textContent(), 'Pause');
  assert.equal(await page.locator('#speed').inputValue(), '325');
  await page.keyboard.press('PageUp'); assert.match(await page.locator('#state').textContent(), /350 WPM/);
  await page.keyboard.down('Space'); await page.keyboard.down('Space'); await page.keyboard.up('Space');
  assert.equal(await page.locator('#play').textContent(), 'Play');
  await page.locator('#speed').focus(); await page.keyboard.press('Enter');
  assert.equal(await page.locator('#play').textContent(), 'Play');
  await page.locator('#speed').fill('300'); await page.locator('#speed').press('Tab');
  await page.locator('dialog').focus();
  const initial = await page.locator('#count').textContent();
  await page.keyboard.press('Space'); await page.waitForTimeout(500); await page.keyboard.press('Space');
  assert.notEqual(await page.locator('#count').textContent(), initial);
  const paused = await page.locator('#count').textContent(); await page.waitForTimeout(300); assert.equal(await page.locator('#count').textContent(), paused);
  await page.getByRole('button', { name: 'Next word', exact: true }).click(); assert.notEqual(await page.locator('#count').textContent(), paused);
  await page.getByRole('button', { name: 'Context', exact: true }).click(); assert.ok(await page.locator('.context').isVisible());
  await page.getByRole('button', { name: 'Switch to dark theme' }).click(); assert.ok(await page.locator('dialog.dark').isVisible());
  await page.getByRole('button', { name: 'Switch to light theme' }).click();
  await page.locator('.stage').hover(); await page.mouse.wheel(0, 220); await page.waitForTimeout(400);
  assert.notEqual(await page.locator('#count').textContent(), paused);
  await page.waitForTimeout(2300); assert.match(await page.locator('#state').textContent(), /Paused/);
  const beforeReverse = Number((await page.locator('#count').textContent()).split(' / ')[0]);
  await page.mouse.wheel(0, -180); await page.waitForTimeout(800);
  assert.ok(Number((await page.locator('#count').textContent()).split(' / ')[0]) < beforeReverse);
  await page.keyboard.press('Escape'); assert.equal(await page.locator('dialog').count(), 0); assert.equal(await page.locator('article').innerHTML(), original);
  assert.equal(await page.evaluate(() => document.activeElement.id), 'open');
  await page.getByRole('button', { name: 'Start reading' }).click();
  assert.equal(await page.getByRole('button', { name: 'Direct', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.getByRole('button', { name: 'Freewheel', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Freewheel', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.locator('.stage').hover(); await page.mouse.wheel(0, 100);
  await page.waitForTimeout(3000); assert.match(await page.locator('#state').textContent(), /Coasting/);
  assert.ok(await page.locator('dialog.reading').count());
  assert.ok(Number(await page.locator('.scroll-feel').evaluate(el => getComputedStyle(el).opacity)) < 0.3);
  const stageBox = await page.locator('.stage').boundingBox();
  const mx = stageBox.x + stageBox.width / 2, my = stageBox.y + stageBox.height / 2;
  await page.mouse.move(mx + 2, my + 2);
  await page.mouse.move(mx - 2, my - 2);
  await page.waitForTimeout(100);
  assert.ok(await page.locator('dialog.reading').count(), 'tiny mouse jitter keeps controls faded');
  await page.mouse.move(mx + 50, my, { steps: 5 });
  await page.waitForTimeout(100);
  assert.equal(await page.locator('dialog.reading').count(), 0, 'deliberate movement reveals controls');

  await page.keyboard.press('Space'); assert.match(await page.locator('#state').textContent(), /Paused/);
  const coastStop = await page.locator('#count').textContent();
  await page.waitForTimeout(300); assert.equal(await page.locator('#count').textContent(), coastStop);
  await page.mouse.wheel(0, 100); await page.getByRole('button', { name: 'Direct', exact: true }).click();
  assert.match(await page.locator('#state').textContent(), /Paused/);
  await page.keyboard.press('Escape');
  // Exercise the actual injected extension bundle, including repeated activation.
  await page.addScriptTag({ url: '/content.js' }); assert.ok(await word.isVisible());
  await page.addScriptTag({ url: '/content.js' }); assert.equal(await page.locator('dialog').count(), 0);
  await page.addScriptTag({ url: '/content.js' });
  await mkdir('.test-results', { recursive: true });
  const demo = new JSDOM(await readFile('dist/demo.html', 'utf8'), { url: 'https://example.com/' });
  const tokens = extract(demo.window.document).tokens;
  const headingIndex = tokens.findIndex(token => token.heading && token.text === 'A pace of your own');
  assert.ok(headingIndex >= 0);
  assert.equal(await page.locator('.section-ticks span').count(), tokens.filter(token => token.heading).length);
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  await page.getByLabel('Jump to section').focus();
  assert.match(await page.locator('#state').textContent(), /Paused/);
  await page.getByLabel('Jump to section').selectOption(String(headingIndex));
  assert.equal(await word.textContent(), 'A pace of your own');
  assert.match(await page.locator('#state').textContent(), /Paused/);
  const progressBox = await page.locator('.progress').boundingBox();
  const headingX = progressBox.x + 8 + headingIndex / (tokens.length - 1) * (progressBox.width - 16);
  await page.mouse.move(headingX + 1, progressBox.y + progressBox.height / 2);
  assert.equal(await page.locator('.section-preview').textContent(), 'A pace of your own');
  assert.ok(await page.locator('.section-preview').isVisible());
  await page.locator('#sections').hover();
  assert.equal(await page.locator('.section-preview').isVisible(), false);

  await page.locator('.progress').evaluate((el, index) => { el.value = String(index); el.dispatchEvent(new Event('input', { bubbles: true })); }, headingIndex);
  assert.equal(await word.textContent(), 'A pace of your own');
  assert.ok(await page.locator('.heading-label').isVisible());
  assert.equal(await word.getAttribute('role'), 'heading');
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  await page.waitForTimeout(500); assert.equal(await word.textContent(), 'A pace of your own');
  await page.waitForFunction(() => !document.querySelector('[data-rsvp-reader]').shadowRoot.querySelector('.stage').classList.contains('heading-card'));
  await page.keyboard.press('Space');
  await page.locator('.progress').evaluate((el, index) => { el.value = String(index); el.dispatchEvent(new Event('input', { bubbles: true })); }, headingIndex);
  await page.screenshot({ path: '.test-results/reader-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.locator('dialog').evaluate(el => el.scrollWidth > el.clientWidth), false);
  await page.screenshot({ path: '.test-results/reader-mobile.png' });
  const bounds = await word.boundingBox(); assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390);
  await page.keyboard.press('Escape');
  await page.evaluate(() => { document.body.innerHTML = '<article><p>' + 'A quiet day gives us time to read and think. '.repeat(30) + '</p></article>'; });
  await page.addScriptTag({ url: '/content.js' });
  assert.equal(await page.locator('.section-nav').isVisible(), false);
  assert.equal(await page.locator('.section-ticks span').count(), 0);
  await page.keyboard.press('Escape');
  await page.evaluate(() => { document.body.innerHTML = '<button id="source">Source</button>'; });
  await page.addScriptTag({ url: '/content.js' }); assert.ok(await page.locator('.error').isVisible());
  await page.keyboard.press('Escape'); assert.equal(await page.locator('dialog').count(), 0);
  await page.goto(`http://127.0.0.1:${server.address().port}/paste.html`);
  await page.getByRole('button', { name: 'Start reading' }).click();
  assert.match(await page.locator('#error').textContent(), /Paste some text/);
  const corpus = '# First section\n\nHello from a document.\nA wrapped line.\n\n## Next section\n\n<script>window.pasteExecuted=true</script> Literal text.';
  await page.locator('#source').fill(corpus);
  await page.locator('#source').press('End');
  await page.keyboard.press('Enter');
  await page.keyboard.type('More words');
  assert.equal(await page.locator('dialog').count(), 0, 'Enter edits the corpus');
  await page.locator('#title').fill('My notes');
  await page.getByRole('button', { name: 'Start reading' }).click();
  assert.equal(await page.locator('.article h1').textContent(), 'My notes');
  assert.equal(await word.textContent(), 'First section');
  assert.equal(await page.locator('#sections option').count(), 2);
  assert.equal(await page.evaluate(() => window.pasteExecuted), undefined);
  await page.keyboard.press('Escape');
  assert.ok((await page.locator('#source').inputValue()).includes('More words'));
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: '.test-results/paste-mobile.png' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: '.test-results/paste-desktop.png' });
  await checkHeadingFocus(page);
  await checkAutoplayWakeLock(page);
  await checkPDFInput(page);
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: play/pause, stepping, context, themes, forward/reverse scrolling, focus restoration, repeated injection, mobile layout, extraction error.');
} finally { await browser.close(); server.close(); }
