import assert from 'node:assert/strict';
export async function checkParagraphView(page) {
  const opening='Hello — world. A (quiet) place. “Read this,” she said. Well-being matters.';
  await page.locator('#source').fill(`# First section\n\n${opening}\n\n${'A longer paragraph keeps its exact reading position. '.repeat(180)}\n\n## Last section\n\nA quiet ending.`);
  await page.getByRole('button',{name:'Start reading',exact:true}).click();
  await page.locator('.progress').fill('5');
  const place=await page.locator('.progress').inputValue();
  const word=await page.locator('.word').textContent();
  await page.locator('#paragraph-view').click();
  assert.equal(await page.locator('#play').textContent(),'Play words');
  assert.equal(await page.locator('.stage').isVisible(),false);
  assert.equal(await page.locator('.progress').inputValue(),place);
  assert.equal(await page.locator('.paragraph-content p').first().textContent(),opening,'paragraph punctuation and spacing survive');
  assert.equal(await page.locator('.current-word').getAttribute('data-token'),place);
  await page.locator('.paragraph-pane').dispatchEvent('wheel',{deltaY:150,bubbles:true,cancelable:true});
  await page.waitForTimeout(150);
  assert.equal(await page.locator('.progress').inputValue(),place,'paragraph wheel does not scrub words');
  await page.locator('#word-view').click();
  assert.equal(await page.locator('.word').textContent(),word);
  assert.equal(await page.locator('#play').textContent(),'Play');
  await page.locator('#play').click();await page.locator('#paragraph-view').click();
  const paused=await page.locator('.progress').inputValue();await page.waitForTimeout(300);
  assert.equal(await page.locator('.progress').inputValue(),paused,'switching to paragraphs pauses autoplay');
  await page.locator('[data-token="12"]').click();
  assert.equal(await page.locator('.progress').inputValue(),'12');
  await page.locator('.paragraph-pane').press('ArrowRight');
  assert.equal(await page.locator('.progress').inputValue(),'13');
  await page.locator('#later-passage').click();
  assert.ok(Number(await page.locator('.progress').inputValue())>500);
  assert.ok(await page.locator('.paragraph-content [data-token]').count()<=600);
  await page.getByLabel('Jump to section').selectOption({label:'Last section'});
  assert.equal(await page.locator('.current-word').textContent(),'Last section');
  await page.locator('#word-view').focus();await page.keyboard.press('Enter');
  assert.equal(await page.locator('.word').textContent(),'Last section');
  assert.equal(await page.locator('#play').textContent(),'Play');
  await page.locator('#paragraph-view').click();await page.locator('#play').click();
  assert.equal(await page.locator('.stage').isVisible(),true);assert.equal(await page.locator('#play').textContent(),'Pause');
  await page.locator('#close').click();
}
